name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          config_timezone: Asia/Shanghai
          base: header, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_sections: base
          plugin_lines_delay: 30
          plugin_languages: yes
          plugin_languages_details: percentage, bytes-size
          plugin_followup: yes
          plugin_followup_sections: user
      - uses: actions/upload-pages-artifact@v3
        with:
          path: /metrics_renders
      - uses: actions/deploy-pages@v4
